# Generated by Django 5.0.6 on 2024-06-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComentarioContacto',
        ),
    ]
